
// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.31.0
// source: protos/assets/assets_common.proto

const { BinaryReader, BinaryWriter } = require("@bufbuild/protobuf/wire");
const { Any } = require("../../google/protobuf/any");

const protobufPackage = "assets";

/** Enum for allowed senders */
const AllowedSender = {
  ALLOWED_SENDER_UNSPECIFIED: 0,
  ALLOWED_SENDER_AUTHENTICATED_GAME: 1,
  ALLOWED_SENDER_AUTHENTICATED_LAUNCHER: 2,
  ALLOWED_SENDER_AUTHENTICATED_GAME_OR_LAUNCHER: 3,
  UNRECOGNIZED: -1,
};

function allowedSenderFromJSON(object) {
  switch (object) {
    case 0:
    case "ALLOWED_SENDER_UNSPECIFIED":
      return AllowedSender.ALLOWED_SENDER_UNSPECIFIED;
    case 1:
    case "ALLOWED_SENDER_AUTHENTICATED_GAME":
      return AllowedSender.ALLOWED_SENDER_AUTHENTICATED_GAME;
    case 2:
    case "ALLOWED_SENDER_AUTHENTICATED_LAUNCHER":
      return AllowedSender.ALLOWED_SENDER_AUTHENTICATED_LAUNCHER;
    case 3:
    case "ALLOWED_SENDER_AUTHENTICATED_GAME_OR_LAUNCHER":
      return AllowedSender.ALLOWED_SENDER_AUTHENTICATED_GAME_OR_LAUNCHER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return AllowedSender.UNRECOGNIZED;
  }
}

function allowedSenderToJSON(object) {
  switch (object) {
    case AllowedSender.ALLOWED_SENDER_UNSPECIFIED:
      return "ALLOWED_SENDER_UNSPECIFIED";
    case AllowedSender.ALLOWED_SENDER_AUTHENTICATED_GAME:
      return "ALLOWED_SENDER_AUTHENTICATED_GAME";
    case AllowedSender.ALLOWED_SENDER_AUTHENTICATED_LAUNCHER:
      return "ALLOWED_SENDER_AUTHENTICATED_LAUNCHER";
    case AllowedSender.ALLOWED_SENDER_AUTHENTICATED_GAME_OR_LAUNCHER:
      return "ALLOWED_SENDER_AUTHENTICATED_GAME_OR_LAUNCHER";
    case AllowedSender.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseServerboundWebSocketMessage() {
  return { requestId: new Uint8Array(0), service: "", method: "", input: new Uint8Array(0) };
}

const ServerboundWebSocketMessage = {
  encode(message, writer = new BinaryWriter()) {
    if (message.requestId.length !== 0) {
      writer.uint32(10).bytes(message.requestId);
    }
    if (message.service !== "") {
      writer.uint32(18).string(message.service);
    }
    if (message.method !== "") {
      writer.uint32(26).string(message.method);
    }
    if (message.input.length !== 0) {
      writer.uint32(34).bytes(message.input);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerboundWebSocketMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.service = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.method = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.input = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      requestId: isSet(object.requestId) ? bytesFromBase64(object.requestId) : new Uint8Array(0),
      service: isSet(object.service) ? String(object.service) : "",
      method: isSet(object.method) ? String(object.method) : "",
      input: isSet(object.input) ? bytesFromBase64(object.input) : new Uint8Array(0),
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.requestId.length !== 0) {
      obj.requestId = base64FromBytes(message.requestId);
    }
    if (message.service !== "") {
      obj.service = message.service;
    }
    if (message.method !== "") {
      obj.method = message.method;
    }
    if (message.input.length !== 0) {
      obj.input = base64FromBytes(message.input);
    }
    return obj;
  },

  create(base) {
    return ServerboundWebSocketMessage.fromPartial(base ?? {});
  },

  fromPartial(object) {
    const message = createBaseServerboundWebSocketMessage();
    message.requestId = object.requestId ?? new Uint8Array(0);
    message.service = object.service ?? "";
    message.method = object.method ?? "";
    message.input = object.input ?? new Uint8Array(0);
    return message;
  },
};

function createBaseClientboundWebSocketMessage() {
  return { rpcResponse: undefined, pushNotification: undefined };
}

const ClientboundWebSocketMessage = {
  encode(message, writer = new BinaryWriter()) {
    if (message.rpcResponse !== undefined) {
      WebSocketRpcResponse.encode(message.rpcResponse, writer.uint32(10).fork()).join();
    }
    if (message.pushNotification !== undefined) {
      Any.encode(message.pushNotification, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientboundWebSocketMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rpcResponse = WebSocketRpcResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pushNotification = Any.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      rpcResponse: isSet(object.rpcResponse) ? WebSocketRpcResponse.fromJSON(object.rpcResponse) : undefined,
      pushNotification: isSet(object.pushNotification) ? Any.fromJSON(object.pushNotification) : undefined,
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.rpcResponse !== undefined) {
      obj.rpcResponse = WebSocketRpcResponse.toJSON(message.rpcResponse);
    }
    if (message.pushNotification !== undefined) {
      obj.pushNotification = Any.toJSON(message.pushNotification);
    }
    return obj;
  },

  create(base) {
    return ClientboundWebSocketMessage.fromPartial(base ?? {});
  },

  fromPartial(object) {
    const message = createBaseClientboundWebSocketMessage();
    message.rpcResponse = (object.rpcResponse !== undefined && object.rpcResponse !== null)
      ? WebSocketRpcResponse.fromPartial(object.rpcResponse)
      : undefined;
    message.pushNotification = (object.pushNotification !== undefined && object.pushNotification !== null)
      ? Any.fromPartial(object.pushNotification)
      : undefined;
    return message;
  },
};

function createBaseWebSocketRpcResponse() {
  return { requestId: new Uint8Array(0), output: new Uint8Array(0) };
}

const WebSocketRpcResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.requestId.length !== 0) {
      writer.uint32(10).bytes(message.requestId);
    }
    if (message.output.length !== 0) {
      writer.uint32(18).bytes(message.output);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWebSocketRpcResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requestId = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.output = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      requestId: isSet(object.requestId) ? bytesFromBase64(object.requestId) : new Uint8Array(0),
      output: isSet(object.output) ? bytesFromBase64(object.output) : new Uint8Array(0),
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.requestId.length !== 0) {
      obj.requestId = base64FromBytes(message.requestId);
    }
    if (message.output.length !== 0) {
      obj.output = base64FromBytes(message.output);
    }
    return obj;
  },

  create(base) {
    return WebSocketRpcResponse.fromPartial(base ?? {});
  },

  fromPartial(object) {
    const message = createBaseWebSocketRpcResponse();
    message.requestId = object.requestId ?? new Uint8Array(0);
    message.output = object.output ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64) {
  if (Buffer) {
    return Uint8Array.from(Buffer.from(b64, "base64"));
  } else {
    const bin = atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr) {
  if (Buffer) {
    return Buffer.from(arr).toString("base64");
  } else {
    const bin = [];
    arr.forEach((byte) => {
      bin.push(String.fromCharCode(byte));
    });
    return btoa(bin.join(""));
  }
}

function isSet(value) {
  return value !== null && value !== undefined;
}

// Export all the necessary components
module.exports = {
  protobufPackage,
  AllowedSender,
  allowedSenderFromJSON,
  allowedSenderToJSON,
  ServerboundWebSocketMessage,
  ClientboundWebSocketMessage,
  WebSocketRpcResponse,
  bytesFromBase64,
  base64FromBytes,
  isSet
};