// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.31.0
// source: protos/common.proto

/* eslint-disable */
const { BinaryReader, BinaryWriter } = require("@bufbuild/protobuf/wire");

const protobufPackage = "protos";

function createBaseUuid() {
  return { high64: 0n, low64: 0n };
}

const Uuid = {
  encode(message, writer = new BinaryWriter()) {
    if (message.high64 !== 0n) {
      if (BigInt.asUintN(64, message.high64) !== message.high64) {
        throw new globalThis.Error("value provided for field message.high64 of type fixed64 too large");
      }
      writer.uint32(9).fixed64(message.high64);
    }
    if (message.low64 !== 0n) {
      if (BigInt.asUintN(64, message.low64) !== message.low64) {
        throw new globalThis.Error("value provided for field message.low64 of type fixed64 too large");
      }
      writer.uint32(17).fixed64(message.low64);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUuid();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 9) {
            break;
          }

          message.high64 = reader.fixed64();
          continue;
        }
        case 2: {
          if (tag !== 17) {
            break;
          }

          message.low64 = reader.fixed64();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      high64: isSet(object.high64) ? BigInt(object.high64) : 0n,
      low64: isSet(object.low64) ? BigInt(object.low64) : 0n,
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.high64 !== 0n) {
      obj.high64 = message.high64.toString();
    }
    if (message.low64 !== 0n) {
      obj.low64 = message.low64.toString();
    }
    return obj;
  },

  create(base) {
    return Uuid.fromPartial(base ?? {});
  },

  fromPartial(object) {
    const message = createBaseUuid();
    message.high64 = object.high64 ?? 0n;
    message.low64 = object.low64 ?? 0n;
    return message;
  },
};

function createBaseUuidAndUsername() {
  return { uuid: undefined, username: "" };
}

const UuidAndUsername = {
  encode(message, writer = new BinaryWriter()) {
    if (message.uuid !== undefined) {
      Uuid.encode(message.uuid, writer.uint32(10).fork()).join();
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUuidAndUsername();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uuid = Uuid.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      uuid: isSet(object.uuid) ? Uuid.fromJSON(object.uuid) : undefined,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.uuid !== undefined) {
      obj.uuid = Uuid.toJSON(message.uuid);
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create(base) {
    return UuidAndUsername.fromPartial(base ?? {});
  },

  fromPartial(object) {
    const message = createBaseUuidAndUsername();
    message.uuid = (object.uuid !== undefined && object.uuid !== null) ? Uuid.fromPartial(object.uuid) : undefined;
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseColor() {
  return { color: 0 };
}

const Color = {
  encode(message, writer = new BinaryWriter()) {
    if (message.color !== 0) {
      writer.uint32(8).int32(message.color);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseColor();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.color = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return { color: isSet(object.color) ? globalThis.Number(object.color) : 0 };
  },

  toJSON(message) {
    const obj = {};
    if (message.color !== 0) {
      obj.color = Math.round(message.color);
    }
    return obj;
  },

  create(base) {
    return Color.fromPartial(base ?? {});
  },

  fromPartial(object) {
    const message = createBaseColor();
    message.color = object.color ?? 0;
    return message;
  },
};

function isSet(value) {
  return value !== null && value !== undefined;
}

// CommonJS exports
module.exports = {
  protobufPackage,
  Uuid,
  UuidAndUsername,
  Color
};