// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.31.0
// source: protos/assets/cosmetics.proto

/* eslint-disable */
const { BinaryReader, BinaryWriter } = require('@bufbuild/protobuf/wire');
const { Struct } = require('../../google/protobuf/struct');
const { Timestamp } = require('../../google/protobuf/timestamp');
const { Color } = require('../common');

const protobufPackage = "lunarclient.websocket.cosmetic.v1";

/** Enum for expiration reasons */
const OwnedCosmeticExpirationReason = {
  EXPIRATION_REASON_UNSPECIFIED: 0,
  /** EXPIRATION_REASON_TIME_LAPSED - Time ran out */
  EXPIRATION_REASON_TIME_LAPSED: 1,
  /** EXPIRATION_REASON_LEFT_LC_DISCORD - Left Lunar Client Discord */
  EXPIRATION_REASON_LEFT_LC_DISCORD: 2,
  UNRECOGNIZED: -1,
};

function ownedCosmeticExpirationReasonFromJSON(object) {
  switch (object) {
    case 0:
    case "EXPIRATION_REASON_UNSPECIFIED":
      return OwnedCosmeticExpirationReason.EXPIRATION_REASON_UNSPECIFIED;
    case 1:
    case "EXPIRATION_REASON_TIME_LAPSED":
      return OwnedCosmeticExpirationReason.EXPIRATION_REASON_TIME_LAPSED;
    case 2:
    case "EXPIRATION_REASON_LEFT_LC_DISCORD":
      return OwnedCosmeticExpirationReason.EXPIRATION_REASON_LEFT_LC_DISCORD;
    case -1:
    case "UNRECOGNIZED":
    default:
      return OwnedCosmeticExpirationReason.UNRECOGNIZED;
  }
}

function ownedCosmeticExpirationReasonToJSON(object) {
  switch (object) {
    case OwnedCosmeticExpirationReason.EXPIRATION_REASON_UNSPECIFIED:
      return "EXPIRATION_REASON_UNSPECIFIED";
    case OwnedCosmeticExpirationReason.EXPIRATION_REASON_TIME_LAPSED:
      return "EXPIRATION_REASON_TIME_LAPSED";
    case OwnedCosmeticExpirationReason.EXPIRATION_REASON_LEFT_LC_DISCORD:
      return "EXPIRATION_REASON_LEFT_LC_DISCORD";
    case OwnedCosmeticExpirationReason.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

function createBaseLoginRequest() {
  return {};
}

const LoginRequest = {
  encode(_, writer = new BinaryWriter()) {
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_) {
    return {};
  },

  toJSON(_) {
    const obj = {};
    return obj;
  },

  create(base) {
    return LoginRequest.fromPartial(base ?? {});
  },
  
  fromPartial(_) {
    const message = createBaseLoginRequest();
    return message;
  },
};

function createBaseLoginResponse() {
  return {
    settings: undefined,
    ownedCosmeticIds: [],
    availableLunarPlusColors: [],
    logoColor: undefined,
    logoAlwaysShow: false,
    lunarPlusFreeCosmeticIds: [],
    ownedCosmetics: [],
    hasAllCosmeticsFlag: false,
    rankName: "",
  };
}

const LoginResponse = {
  encode(message, writer = new BinaryWriter()) {
    if (message.settings !== undefined) {
      CustomizableCosmeticSettings.encode(message.settings, writer.uint32(10).fork()).join();
    }
    writer.uint32(18).fork();
    for (const v of message.ownedCosmeticIds) {
      writer.int32(v);
    }
    writer.join();
    for (const v of message.availableLunarPlusColors) {
      Color.encode(v, writer.uint32(26).fork()).join();
    }
    if (message.logoColor !== undefined) {
      Color.encode(message.logoColor, writer.uint32(34).fork()).join();
    }
    if (message.logoAlwaysShow !== false) {
      writer.uint32(40).bool(message.logoAlwaysShow);
    }
    writer.uint32(50).fork();
    for (const v of message.lunarPlusFreeCosmeticIds) {
      writer.int32(v);
    }
    writer.join();
    for (const v of message.ownedCosmetics) {
      OwnedCosmetic.encode(v, writer.uint32(58).fork()).join();
    }
    if (message.hasAllCosmeticsFlag !== false) {
      writer.uint32(64).bool(message.hasAllCosmeticsFlag);
    }
    if (message.rankName !== "") {
      writer.uint32(74).string(message.rankName);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.settings = CustomizableCosmeticSettings.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag === 16) {
            message.ownedCosmeticIds.push(reader.int32());

            continue;
          }

          if (tag === 18) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.ownedCosmeticIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.availableLunarPlusColors.push(Color.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.logoColor = Color.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.logoAlwaysShow = reader.bool();
          continue;
        }
        case 6: {
          if (tag === 48) {
            message.lunarPlusFreeCosmeticIds.push(reader.int32());

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.lunarPlusFreeCosmeticIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.ownedCosmetics.push(OwnedCosmetic.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.hasAllCosmeticsFlag = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.rankName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      settings: isSet(object.settings) ? CustomizableCosmeticSettings.fromJSON(object.settings) : undefined,
      ownedCosmeticIds: globalThis.Array.isArray(object?.ownedCosmeticIds)
        ? object.ownedCosmeticIds.map((e) => globalThis.Number(e))
        : [],
      availableLunarPlusColors: globalThis.Array.isArray(object?.availableLunarPlusColors)
        ? object.availableLunarPlusColors.map((e) => Color.fromJSON(e))
        : [],
      logoColor: isSet(object.logoColor) ? Color.fromJSON(object.logoColor) : undefined,
      logoAlwaysShow: isSet(object.logoAlwaysShow) ? globalThis.Boolean(object.logoAlwaysShow) : false,
      lunarPlusFreeCosmeticIds: globalThis.Array.isArray(object?.lunarPlusFreeCosmeticIds)
        ? object.lunarPlusFreeCosmeticIds.map((e) => globalThis.Number(e))
        : [],
      ownedCosmetics: globalThis.Array.isArray(object?.ownedCosmetics)
        ? object.ownedCosmetics.map((e) => OwnedCosmetic.fromJSON(e))
        : [],
      hasAllCosmeticsFlag: isSet(object.hasAllCosmeticsFlag) ? globalThis.Boolean(object.hasAllCosmeticsFlag) : false,
      rankName: isSet(object.rankName) ? globalThis.String(object.rankName) : "",
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.settings !== undefined) {
      obj.settings = CustomizableCosmeticSettings.toJSON(message.settings);
    }
    if (message.ownedCosmeticIds?.length) {
      obj.ownedCosmeticIds = message.ownedCosmeticIds.map((e) => Math.round(e));
    }
    if (message.availableLunarPlusColors?.length) {
      obj.availableLunarPlusColors = message.availableLunarPlusColors.map((e) => Color.toJSON(e));
    }
    if (message.logoColor !== undefined) {
      obj.logoColor = Color.toJSON(message.logoColor);
    }
    if (message.logoAlwaysShow !== false) {
      obj.logoAlwaysShow = message.logoAlwaysShow;
    }
    if (message.lunarPlusFreeCosmeticIds?.length) {
      obj.lunarPlusFreeCosmeticIds = message.lunarPlusFreeCosmeticIds.map((e) => Math.round(e));
    }
    if (message.ownedCosmetics?.length) {
      obj.ownedCosmetics = message.ownedCosmetics.map((e) => OwnedCosmetic.toJSON(e));
    }
    if (message.hasAllCosmeticsFlag !== false) {
      obj.hasAllCosmeticsFlag = message.hasAllCosmeticsFlag;
    }
    if (message.rankName !== "") {
      obj.rankName = message.rankName;
    }
    return obj;
  },

  create(base) {
    return LoginResponse.fromPartial(base ?? {});
  },
  
  fromPartial(object) {
    const message = createBaseLoginResponse();
    message.settings = (object.settings !== undefined && object.settings !== null)
      ? CustomizableCosmeticSettings.fromPartial(object.settings)
      : undefined;
    message.ownedCosmeticIds = object.ownedCosmeticIds?.map((e) => e) || [];
    message.availableLunarPlusColors = object.availableLunarPlusColors?.map((e) => Color.fromPartial(e)) || [];
    message.logoColor = (object.logoColor !== undefined && object.logoColor !== null)
      ? Color.fromPartial(object.logoColor)
      : undefined;
    message.logoAlwaysShow = object.logoAlwaysShow ?? false;
    message.lunarPlusFreeCosmeticIds = object.lunarPlusFreeCosmeticIds?.map((e) => e) || [];
    message.ownedCosmetics = object.ownedCosmetics?.map((e) => OwnedCosmetic.fromPartial(e)) || [];
    message.hasAllCosmeticsFlag = object.hasAllCosmeticsFlag ?? false;
    message.rankName = object.rankName ?? "";
    return message;
  },
};

function createBaseUpdateCosmeticSettingsRequest() {
  return { settings: undefined };
}

const UpdateCosmeticSettingsRequest = {
  encode(message, writer = new BinaryWriter()) {
    if (message.settings !== undefined) {
      CustomizableCosmeticSettings.encode(message.settings, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCosmeticSettingsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.settings = CustomizableCosmeticSettings.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return { settings: isSet(object.settings) ? CustomizableCosmeticSettings.fromJSON(object.settings) : undefined };
  },

  toJSON(message) {
    const obj = {};
    if (message.settings !== undefined) {
      obj.settings = CustomizableCosmeticSettings.toJSON(message.settings);
    }
    return obj;
  },

  create(base) {
    return UpdateCosmeticSettingsRequest.fromPartial(base ?? {});
  },
  
  fromPartial(object) {
    const message = createBaseUpdateCosmeticSettingsRequest();
    message.settings = (object.settings !== undefined && object.settings !== null)
      ? CustomizableCosmeticSettings.fromPartial(object.settings)
      : undefined;
    return message;
  },
};

function createBaseUpdateCosmeticSettingsResponse() {
  return {};
}

const UpdateCosmeticSettingsResponse = {
  encode(_, writer = new BinaryWriter()) {
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateCosmeticSettingsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_) {
    return {};
  },

  toJSON(_) {
    const obj = {};
    return obj;
  },

  create(base) {
    return UpdateCosmeticSettingsResponse.fromPartial(base ?? {});
  },
  
  fromPartial(_) {
    const message = createBaseUpdateCosmeticSettingsResponse();
    return message;
  },
};

function createBaseCustomizableCosmeticSettings() {
  return {
    activeCosmeticIds: [],
    clothCloak: false,
    plusColor: undefined,
    showHatsOverHelmet: false,
    showHatsOverSkinLayer: false,
    showOverChestplate: false,
    showOverLeggings: false,
    showOverBoots: false,
    hatHeightOffset: {},
    flipShoulderPet: false,
    equippedCosmetics: [],
  };
}

const CustomizableCosmeticSettings = {
  encode(message, writer = new BinaryWriter()) {
    writer.uint32(10).fork();
    for (const v of message.activeCosmeticIds) {
      writer.int32(v);
    }
    writer.join();
    if (message.clothCloak !== false) {
      writer.uint32(16).bool(message.clothCloak);
    }
    if (message.plusColor !== undefined) {
      Color.encode(message.plusColor, writer.uint32(26).fork()).join();
    }
    if (message.showHatsOverHelmet !== false) {
      writer.uint32(32).bool(message.showHatsOverHelmet);
    }
    if (message.showHatsOverSkinLayer !== false) {
      writer.uint32(40).bool(message.showHatsOverSkinLayer);
    }
    if (message.showOverChestplate !== false) {
      writer.uint32(48).bool(message.showOverChestplate);
    }
    if (message.showOverLeggings !== false) {
      writer.uint32(56).bool(message.showOverLeggings);
    }
    if (message.showOverBoots !== false) {
      writer.uint32(64).bool(message.showOverBoots);
    }
    Object.entries(message.hatHeightOffset).forEach(([key, value]) => {
      CustomizableCosmeticSettings_HatHeightOffsetEntry.encode({ key: key, value }, writer.uint32(74).fork())
        .join();
    });
    if (message.flipShoulderPet !== false) {
      writer.uint32(80).bool(message.flipShoulderPet);
    }
    for (const v of message.equippedCosmetics) {
      EquippedCosmetic.encode(v, writer.uint32(90).fork()).join();
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomizableCosmeticSettings();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.activeCosmeticIds.push(reader.int32());

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.activeCosmeticIds.push(reader.int32());
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.clothCloak = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.plusColor = Color.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.showHatsOverHelmet = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.showHatsOverSkinLayer = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.showOverChestplate = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.showOverLeggings = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.showOverBoots = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          const entry9 = CustomizableCosmeticSettings_HatHeightOffsetEntry.decode(reader, reader.uint32());
          if (entry9.value !== undefined) {
            message.hatHeightOffset[entry9.key] = entry9.value;
          }
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.flipShoulderPet = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.equippedCosmetics.push(EquippedCosmetic.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      activeCosmeticIds: globalThis.Array.isArray(object?.activeCosmeticIds)
        ? object.activeCosmeticIds.map((e) => globalThis.Number(e))
        : [],
      clothCloak: isSet(object.clothCloak) ? globalThis.Boolean(object.clothCloak) : false,
      plusColor: isSet(object.plusColor) ? Color.fromJSON(object.plusColor) : undefined,
      showHatsOverHelmet: isSet(object.showHatsOverHelmet) ? globalThis.Boolean(object.showHatsOverHelmet) : false,
      showHatsOverSkinLayer: isSet(object.showHatsOverSkinLayer)
        ? globalThis.Boolean(object.showHatsOverSkinLayer)
        : false,
      showOverChestplate: isSet(object.showOverChestplate) ? globalThis.Boolean(object.showOverChestplate) : false,
      showOverLeggings: isSet(object.showOverLeggings) ? globalThis.Boolean(object.showOverLeggings) : false,
      showOverBoots: isSet(object.showOverBoots) ? globalThis.Boolean(object.showOverBoots) : false,
      hatHeightOffset: isObject(object.hatHeightOffset)
        ? Object.entries(object.hatHeightOffset).reduce((acc, [key, value]) => {
          acc[globalThis.Number(key)] = Number(value);
          return acc;
        }, {})
        : {},
      flipShoulderPet: isSet(object.flipShoulderPet) ? globalThis.Boolean(object.flipShoulderPet) : false,
      equippedCosmetics: globalThis.Array.isArray(object?.equippedCosmetics)
        ? object.equippedCosmetics.map((e) => EquippedCosmetic.fromJSON(e))
        : [],
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.activeCosmeticIds?.length) {
      obj.activeCosmeticIds = message.activeCosmeticIds.map((e) => Math.round(e));
    }
    if (message.clothCloak !== false) {
      obj.clothCloak = message.clothCloak;
    }
    if (message.plusColor !== undefined) {
      obj.plusColor = Color.toJSON(message.plusColor);
    }
    if (message.showHatsOverHelmet !== false) {
      obj.showHatsOverHelmet = message.showHatsOverHelmet;
    }
    if (message.showHatsOverSkinLayer !== false) {
      obj.showHatsOverSkinLayer = message.showHatsOverSkinLayer;
    }
    if (message.showOverChestplate !== false) {
      obj.showOverChestplate = message.showOverChestplate;
    }
    if (message.showOverLeggings !== false) {
      obj.showOverLeggings = message.showOverLeggings;
    }
    if (message.showOverBoots !== false) {
      obj.showOverBoots = message.showOverBoots;
    }
    if (message.hatHeightOffset) {
      const entries = Object.entries(message.hatHeightOffset);
      if (entries.length > 0) {
        obj.hatHeightOffset = {};
        entries.forEach(([k, v]) => {
          obj.hatHeightOffset[k] = v;
        });
      }
    }
    if (message.flipShoulderPet !== false) {
      obj.flipShoulderPet = message.flipShoulderPet;
    }
    if (message.equippedCosmetics?.length) {
      obj.equippedCosmetics = message.equippedCosmetics.map((e) => EquippedCosmetic.toJSON(e));
    }
    return obj;
  },

  create(base) {
    return CustomizableCosmeticSettings.fromPartial(base ?? {});
  },
  
  fromPartial(object) {
    const message = createBaseCustomizableCosmeticSettings();
    message.activeCosmeticIds = object.activeCosmeticIds?.map((e) => e) || [];
    message.clothCloak = object.clothCloak ?? false;
    message.plusColor = (object.plusColor !== undefined && object.plusColor !== null)
      ? Color.fromPartial(object.plusColor)
      : undefined;
    message.showHatsOverHelmet = object.showHatsOverHelmet ?? false;
    message.showHatsOverSkinLayer = object.showHatsOverSkinLayer ?? false;
    message.showOverChestplate = object.showOverChestplate ?? false;
    message.showOverLeggings = object.showOverLeggings ?? false;
    message.showOverBoots = object.showOverBoots ?? false;
    message.hatHeightOffset = Object.entries(object.hatHeightOffset ?? {}).reduce(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.flipShoulderPet = object.flipShoulderPet ?? false;
    message.equippedCosmetics = object.equippedCosmetics?.map((e) => EquippedCosmetic.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCustomizableCosmeticSettings_HatHeightOffsetEntry() {
  return { key: 0, value: 0 };
}

const CustomizableCosmeticSettings_HatHeightOffsetEntry = {
  encode(message, writer = new BinaryWriter()) {
    if (message.key !== 0) {
      writer.uint32(8).int32(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(21).float(message.value);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCustomizableCosmeticSettings_HatHeightOffsetEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.value = reader.float();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== 0) {
      obj.value = message.value;
    }
    return obj;
  },

  create(base) {
    return CustomizableCosmeticSettings_HatHeightOffsetEntry.fromPartial(base ?? {});
  },
  
  fromPartial(object) {
    const message = createBaseCustomizableCosmeticSettings_HatHeightOffsetEntry();
    message.key = object.key ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

function createBaseEquippedCosmetic() {
  return { cosmeticId: 0, metadata: undefined };
}

const EquippedCosmetic = {
  encode(message, writer = new BinaryWriter()) {
    if (message.cosmeticId !== 0) {
      writer.uint32(8).int32(message.cosmeticId);
    }
    if (message.metadata !== undefined) {
      Struct.encode(Struct.wrap(message.metadata), writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEquippedCosmetic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cosmeticId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.metadata = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      cosmeticId: isSet(object.cosmeticId) ? globalThis.Number(object.cosmeticId) : 0,
      metadata: isObject(object.metadata) ? object.metadata : undefined,
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.cosmeticId !== 0) {
      obj.cosmeticId = Math.round(message.cosmeticId);
    }
    if (message.metadata !== undefined) {
      obj.metadata = message.metadata;
    }
    return obj;
  },

  create(base) {
    return EquippedCosmetic.fromPartial(base ?? {});
  },
  
  fromPartial(object) {
    const message = createBaseEquippedCosmetic();
    message.cosmeticId = object.cosmeticId ?? 0;
    message.metadata = object.metadata ?? undefined;
    return message;
  },
};

function createBaseOwnedCosmetic() {
  return { cosmeticId: 0, grantedAt: undefined, expiresAt: undefined, expirationReason: 0 };
}

const OwnedCosmetic = {
  encode(message, writer = new BinaryWriter()) {
    if (message.cosmeticId !== 0) {
      writer.uint32(8).int32(message.cosmeticId);
    }
    if (message.grantedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.grantedAt), writer.uint32(18).fork()).join();
    }
    if (message.expiresAt !== undefined) {
      Timestamp.encode(toTimestamp(message.expiresAt), writer.uint32(26).fork()).join();
    }
    if (message.expirationReason !== 0) {
      writer.uint32(32).int32(message.expirationReason);
    }
    return writer;
  },

  decode(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOwnedCosmetic();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.cosmeticId = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.grantedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.expiresAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.expirationReason = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object) {
    return {
      cosmeticId: isSet(object.cosmeticId) ? globalThis.Number(object.cosmeticId) : 0,
      grantedAt: isSet(object.grantedAt) ? fromJsonTimestamp(object.grantedAt) : undefined,
      expiresAt: isSet(object.expiresAt) ? fromJsonTimestamp(object.expiresAt) : undefined,
      expirationReason: isSet(object.expirationReason)
        ? ownedCosmeticExpirationReasonFromJSON(object.expirationReason)
        : 0,
    };
  },

  toJSON(message) {
    const obj = {};
    if (message.cosmeticId !== 0) {
      obj.cosmeticId = Math.round(message.cosmeticId);
    }
    if (message.grantedAt !== undefined) {
      obj.grantedAt = message.grantedAt.toISOString();
    }
    if (message.expiresAt !== undefined) {
      obj.expiresAt = message.expiresAt.toISOString();
    }
    if (message.expirationReason !== 0) {
      obj.expirationReason = ownedCosmeticExpirationReasonToJSON(message.expirationReason);
    }
    return obj;
  },

  create(base) {
    return OwnedCosmetic.fromPartial(base ?? {});
  },
  
  fromPartial(object) {
    const message = createBaseOwnedCosmetic();
    message.cosmeticId = object.cosmeticId ?? 0;
    message.grantedAt = object.grantedAt ?? undefined;
    message.expiresAt = object.expiresAt ?? undefined;
    message.expirationReason = object.expirationReason ?? 0;
    return message;
  },
};

function toTimestamp(date) {
  const seconds = BigInt(Math.trunc(date.getTime() / 1_000));
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t) {
  let millis = (globalThis.Number(t.seconds.toString()) || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o) {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function isObject(value) {
  return typeof value === "object" && value !== null;
}

function isSet(value) {
  return value !== null && value !== undefined;
}

module.exports = {
  protobufPackage,
  OwnedCosmeticExpirationReason,
  ownedCosmeticExpirationReasonFromJSON,
  ownedCosmeticExpirationReasonToJSON,
  LoginRequest,
  LoginResponse,
  UpdateCosmeticSettingsRequest,
  UpdateCosmeticSettingsResponse,
  CustomizableCosmeticSettings,
  CustomizableCosmeticSettings_HatHeightOffsetEntry,
  EquippedCosmetic,
  OwnedCosmetic,
};