// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
// protoc-gen-ts_proto v2.7.0
// protoc v6.31.0
// source: protos/assets/push.proto
/* eslint-disable */

const { BinaryReader, BinaryWriter } = require("@bufbuild/protobuf/wire");
const { Uuid } = require("../common");

const protobufPackage = "assets";

function createBaseSessionIdentifyPush() {
  return { sessionId: undefined };
}

const SessionIdentifyPush = {
  encode: function(message, writer = new BinaryWriter()) {
    if (message.sessionId !== undefined) {
      Uuid.encode(message.sessionId, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode: function(input, length) {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionIdentifyPush();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }
          message.sessionId = Uuid.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON: function(object) {
    return { sessionId: isSet(object.sessionId) ? Uuid.fromJSON(object.sessionId) : undefined };
  },

  toJSON: function(message) {
    const obj = {};
    if (message.sessionId !== undefined) {
      obj.sessionId = Uuid.toJSON(message.sessionId);
    }
    return obj;
  },

  create: function(base) {
    return SessionIdentifyPush.fromPartial(base || {});
  },

  fromPartial: function(object) {
    const message = createBaseSessionIdentifyPush();
    message.sessionId = (object.sessionId !== undefined && object.sessionId !== null)
      ? Uuid.fromPartial(object.sessionId)
      : undefined;
    return message;
  }
};

function isSet(value) {
  return value !== null && value !== undefined;
}

// Exports
module.exports = {
  protobufPackage,
  SessionIdentifyPush,
  createBaseSessionIdentifyPush
};